[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "aws-s3-explorer-mcp"
version = "0.1.1"
description = "An open-source Model Context Protocol (MCP) server for Amazon S3."
readme = "README.md"
requires-python = ">=3.11"
license = {text = "MIT"}
authors = [
  {name = "Kyle Bates", email = "kylembates97@gmail.com"}
]
# These are the actual packages pip will install alongside your code
dependencies = [
    "mcp",
    "aiobotocore"
]

# This is the magic part: it creates a command-line tool automatically
[project.scripts]
aws-s3-mcp = "aws_s3_mcp.server:main"

[tool.setuptools.packages.find]
where = ["src"]