[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "aws-s3-explorer-mcp"
version = "0.1.4"
description = "An open-source Model Context Protocol (MCP) server for Amazon S3."
readme = "README.md"
requires-python = ">=3.11"
license = {text = "MIT"}
authors = [
  {name = "Kyle Bates", email = "kylembates97@gmail.com"}
]
dependencies = [
    "mcp",
    "aiobotocore"
]

[project.urls]
Homepage = "https://github.com/kbates97/AWS_S3_Explorer_MCP.git"
Repository = "https://github.com/kbates97/AWS_S3_Explorer_MCP.git"

[project.scripts]
aws-s3-explorer-mcp = "aws_s3_mcp.server:main"

[tool.setuptools.packages.find]
where = ["src"]